### ISSUE TITLE
Link 35 is broken

### ISSUE THREAD

**Issue by Leon0402** [dvgodoy/PyTorchStepByStep#2]
Another thing I found in the book, link 35 doesn't seem to work.

Thanks! :)

**Comment by dvgodoy** [comment]
Hi,

Could you please give me more info:
- which OS are you using?
- did you try opening the PDF in the browser or using Adobe Acrobat Reader?
- if it was Acrobat, which version?

I ask you this because there seems to be an issue with Adobe and MacOS with links using "#" (that gets converted to %23 and show up as broken), which was the case for link 35 (and PyTorch documentation links as well).

Thanks for pointing it out!

**Comment by Leon0402** [comment]
In deed it was on mac os, although I don't think it was adobe reader. I think it was the default mac os reader, which opended. But I gotta check that again.

On my Linux Machine, I usually use, I don't have the problem as you assumed.

**Comment by dvgodoy** [comment]
Thanks for the information. I've shortened the URLs with "#" in it, so it should work independently of the OS or PDF reader.
You can already download the newest version from Leanpuib and it should work :-)

Once again, thank you very much for support my work and helping to fix these issues :-)
