### ISSUE TITLE
The use of the module `data_generation` in chapter 4

### ISSUE THREAD

**Issue by NnannaOmoke** [dvgodoy/PyTorchStepByStep#45]
Chapter 4, when defining Imports
`from data_generation.image_classification import generate_dataset`

In the `data_generation` package as of 15/11/23, the sub_module `image_classification` no longer seems to exist. Are there any alternatives, so I may proceed with the chapter?

**Comment by dvgodoy** [comment]
Hi @NnannaOmoke 

Thank you for your message.
Are you running it on Google Colab? I just tried it out and it seems to be working there.
The `image_classification` submodule that's imported can be found in the repo too:

https://github.com/dvgodoy/PyTorchStepByStep/blob/master/data_generation/image_classification.py

In Colab, these files should be downloaded by running the `config_chapter4()` function.

If you're running it locally, perhaps the file was removed. Please try either downloading it and placing it inside the `data_generation` folder where you're running the notebook, or, if you cloned the whole repo, you can also use `git pull` to retrieve the missing file directly from GitHub.

I hope this solves the issue.

Best,
Daniel

**Comment by NnannaOmoke** [comment]
Thank you very much Mr. Godoy. I am actually running it (my notebooks) on VSCode, as I performed the setup of `jupyter` ,`ipython` and other packages manually. Cloning the repository and porting the folder data_generation to my working directory fixed the issue.

I must let you know that your book is perhaps the most clear and concise book I've come across on Deep Learning. As a computer science student pursuing a future in data science and ML, it has been a massive help. While I'm familiar with Tensorflow and Sci-kit Learn, will there be any books in the future coming out on those? Also, several concepts were mentioned to be _out of the scope of this book_. Are we going to get anything more in depth in the future too?

Again, thank you so very much for writing this book. I also really appreciate your timely reply Have a nice day, Mr. Godoy!

**Comment by dvgodoy** [comment]
Thank you for your kind words and the amazing feedback :-) I am happy to hear my book is so helpful to you!

I had the idea of writing a book focused on traditional ML and Scikit-Learn, but I'm not sure if this still makes sense in a post-ChatGPT world, to be honest. Won't be doing anything with TensorFlow, that's for sure.

Regarding concepts out of the scope, I had to draw the line somewhere because the book already had 1,000 pages :-)
If you'd like some materials on ML, please check a repo I developed to teach a class a few years ago:

https://github.com/dvgodoy/ML_Fundamentals

Hopefully it will help with some concepts that weren't covered in the PyTorch book, such as train-validation split, etc.

Best,
Daniel
