### ISSUE TITLE
ImageFolder: a generic dataset or data loader?

### ISSUE THREAD

**Issue by Patrick-Wen** [dvgodoy/PyTorchStepByStep#48]
Here is a description of ImageFolder in Page 419 of the book:
![Snipaste_2024-03-21_15-52-32](https://github.com/dvgodoy/PyTorchStepByStep/assets/100295693/0bdc6e4f-067a-4525-86c6-56f0018c9a46)

In contrast to the above description of ImageFolder as a "_generic dataset_", the PyTorch user manual describes ImageFolder as "A _generic data loader_ where the images are arranged in this way by default ...". I feel ImageFolder functions like TensorDataset but is specifically for image data. I am not sure whether to call it a generic dataset or generic data loader. 

All I know about PyTorch is from this book for the moment and I am just on my way of learning. Any clarification is appreciated. Thank you.

**Comment by dvgodoy** [comment]
Hi @Patrick-Wen 

I see your point - PyTorch's documentation says it is a "generic data loader" and it may be confusing. It is indeed possible to interpret it as data loader, since it's just retrieving data organized in a certain way (one folder for class), but it is not a `DataLoader` (as in the class definition).

If we look at the classes, `ImageFolder` inherits from `DatasetFolder` which is inherited from `VisionDataset`. These classes implement the typical dataset methods: `__getitem__`, `__init__`, and `__len__`.

In PyTorch's own "[Datasets & DataLoaders](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html)" it states: _"A custom `Dataset` class must implement three functions: `__init__`,` __len__`, and `__getitem__`"_

An actual `DataLoder` does not implement `__getitem__`, it is an iterator so it implements `__iter__` instead. In the documentation it states that "_Data loader combines a dataset and a sampler, and provides an iterable over the given dataset._"

So, while the `ImageFolder` only "loads data" (and that's why I think they called it a generic data loader), it is not a true `DataLoader` (which you use to create mini-batches) because it is implemented as a `Dataset` (which you use to retrieve individual data points).

I hope this helps!

Best,
Daniel
